-- ============================================================
-- BLOQUE 38.2
-- Propuesta economica del especialista y aceptacion del paciente
-- ============================================================

-- ------------------------------------------------------------
-- 1. Propuestas economicas para solicitudes medicas
-- ------------------------------------------------------------

CREATE TABLE medical_request_proposals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medical_request_id BIGINT NOT NULL,
    specialist_profile_id BIGINT NOT NULL,

    service_amount NUMERIC(10,2) NOT NULL,
    mobility_policy_snapshot VARCHAR(30) NOT NULL,
    mobility_amount NUMERIC(10,2) NOT NULL DEFAULT 0,
    total_amount NUMERIC(10,2) NOT NULL,
    currency VARCHAR(10) NOT NULL DEFAULT 'PEN',

    proposal_message VARCHAR(500),
    estimated_arrival_minutes INTEGER NOT NULL,

    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    expires_at TIMESTAMPTZ NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    responded_at TIMESTAMPTZ,
    withdrawn_at TIMESTAMPTZ,

    CONSTRAINT fk_medical_request_proposals_request
        FOREIGN KEY (medical_request_id)
        REFERENCES medical_requests(id),

    CONSTRAINT fk_medical_request_proposals_specialist
        FOREIGN KEY (specialist_profile_id)
        REFERENCES specialist_profiles(id),

    CONSTRAINT chk_medical_request_proposals_service_amount
        CHECK (service_amount > 0),

    CONSTRAINT chk_medical_request_proposals_mobility
        CHECK (
            (
                mobility_policy_snapshot = 'INCLUDED'
                AND mobility_amount = 0
            )
            OR
            (
                mobility_policy_snapshot = 'SEPARATE'
                AND mobility_amount > 0
            )
        ),

    CONSTRAINT chk_medical_request_proposals_total
        CHECK (
            total_amount = service_amount + mobility_amount
            AND total_amount > 0
        ),

    CONSTRAINT chk_medical_request_proposals_currency
        CHECK (currency = 'PEN'),

    CONSTRAINT chk_medical_request_proposals_arrival
        CHECK (
            estimated_arrival_minutes BETWEEN 1 AND 1440
        ),

    CONSTRAINT chk_medical_request_proposals_status
        CHECK (
            status IN (
                'PENDING',
                'ACCEPTED',
                'REJECTED',
                'WITHDRAWN',
                'EXPIRED'
            )
        ),

    CONSTRAINT chk_medical_request_proposals_expiration
        CHECK (expires_at > created_at),

    CONSTRAINT chk_medical_request_proposals_responded_at
        CHECK (
            responded_at IS NULL
            OR responded_at >= created_at
        ),

    CONSTRAINT chk_medical_request_proposals_withdrawn_at
        CHECK (
            withdrawn_at IS NULL
            OR withdrawn_at >= created_at
        )
);

-- ------------------------------------------------------------
-- 2. Indices de consulta y concurrencia
-- ------------------------------------------------------------

CREATE INDEX idx_medical_request_proposals_request_status
    ON medical_request_proposals (
        medical_request_id,
        status
    );

CREATE INDEX idx_medical_request_proposals_specialist_status
    ON medical_request_proposals (
        specialist_profile_id,
        status
    );

CREATE INDEX idx_medical_request_proposals_expiration
    ON medical_request_proposals (
        status,
        expires_at
    );

-- Un especialista solo puede mantener una propuesta pendiente
-- para la misma solicitud.

CREATE UNIQUE INDEX uq_medical_request_proposals_pending
    ON medical_request_proposals (
        medical_request_id,
        specialist_profile_id
    )
    WHERE status = 'PENDING';

-- Una solicitud solo puede tener una propuesta aceptada.

CREATE UNIQUE INDEX uq_medical_request_proposals_accepted
    ON medical_request_proposals (
        medical_request_id
    )
    WHERE status = 'ACCEPTED';

-- ------------------------------------------------------------
-- 3. Trazabilidad de la propuesta aceptada en la solicitud
-- ------------------------------------------------------------

ALTER TABLE medical_requests
    ADD COLUMN accepted_proposal_id BIGINT;

ALTER TABLE medical_requests
    ADD CONSTRAINT chk_medical_requests_accepted_proposal_specialist
    CHECK (
        accepted_proposal_id IS NULL
        OR accepted_specialist_profile_id IS NOT NULL
    );

-- Identidad compuesta utilizada para comprobar que la propuesta
-- aceptada pertenece a la misma solicitud y al mismo especialista.

CREATE UNIQUE INDEX uq_medical_request_proposals_acceptance_link
    ON medical_request_proposals (
        id,
        medical_request_id,
        specialist_profile_id
    );

ALTER TABLE medical_requests
    ADD CONSTRAINT fk_medical_requests_accepted_proposal
    FOREIGN KEY (
        accepted_proposal_id,
        id,
        accepted_specialist_profile_id
    )
    REFERENCES medical_request_proposals (
        id,
        medical_request_id,
        specialist_profile_id
    );

CREATE UNIQUE INDEX uq_medical_requests_accepted_proposal
    ON medical_requests (
        accepted_proposal_id
    )
    WHERE accepted_proposal_id IS NOT NULL;
