-- ============================================================
-- BLOQUE 38.3
-- Adicionales durante la atencion y decision del paciente
-- ============================================================

CREATE TABLE medical_request_additionals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medical_request_id BIGINT NOT NULL,
    specialist_profile_id BIGINT NOT NULL,

    concept VARCHAR(120) NOT NULL,
    justification VARCHAR(1000) NOT NULL,
    amount NUMERIC(10,2) NOT NULL,
    currency VARCHAR(10) NOT NULL DEFAULT 'PEN',

    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    responded_at TIMESTAMPTZ,
    withdrawn_at TIMESTAMPTZ,

    CONSTRAINT fk_medical_request_additionals_request
        FOREIGN KEY (medical_request_id)
        REFERENCES medical_requests(id),

    CONSTRAINT fk_medical_request_additionals_specialist
        FOREIGN KEY (specialist_profile_id)
        REFERENCES specialist_profiles(id),

    CONSTRAINT chk_medical_request_additionals_concept
        CHECK (
            char_length(btrim(concept)) BETWEEN 3 AND 120
        ),

    CONSTRAINT chk_medical_request_additionals_justification
        CHECK (
            char_length(btrim(justification)) BETWEEN 10 AND 1000
        ),

    CONSTRAINT chk_medical_request_additionals_amount
        CHECK (amount > 0),

    CONSTRAINT chk_medical_request_additionals_currency
        CHECK (currency = 'PEN'),

    CONSTRAINT chk_medical_request_additionals_status
        CHECK (
            status IN (
                'PENDING',
                'APPROVED',
                'REJECTED',
                'WITHDRAWN'
            )
        ),

    CONSTRAINT chk_medical_request_additionals_dates
        CHECK (
            (
                status = 'PENDING'
                AND responded_at IS NULL
                AND withdrawn_at IS NULL
            )
            OR
            (
                status IN ('APPROVED', 'REJECTED')
                AND responded_at IS NOT NULL
                AND responded_at >= created_at
                AND withdrawn_at IS NULL
            )
            OR
            (
                status = 'WITHDRAWN'
                AND responded_at IS NULL
                AND withdrawn_at IS NOT NULL
                AND withdrawn_at >= created_at
            )
        )
);

CREATE INDEX idx_medical_request_additionals_request_status
    ON medical_request_additionals (
        medical_request_id,
        status
    );

CREATE INDEX idx_medical_request_additionals_specialist_status
    ON medical_request_additionals (
        specialist_profile_id,
        status
    );

CREATE INDEX idx_medical_request_additionals_created_at
    ON medical_request_additionals (
        medical_request_id,
        created_at,
        id
    );

CREATE OR REPLACE FUNCTION validate_medical_request_additional()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    request_status VARCHAR(40);
    assigned_specialist_id BIGINT;
BEGIN
    SELECT
        status,
        accepted_specialist_profile_id
    INTO
        request_status,
        assigned_specialist_id
    FROM medical_requests
    WHERE id = NEW.medical_request_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION
            'La solicitud medica % no existe.',
            NEW.medical_request_id;
    END IF;

    IF request_status <> 'EN_ATENCION' THEN
        RAISE EXCEPTION
            'Los adicionales solo pueden gestionarse durante EN_ATENCION. Estado actual: %.',
            request_status;
    END IF;

    IF assigned_specialist_id IS NULL
       OR assigned_specialist_id <> NEW.specialist_profile_id
    THEN
        RAISE EXCEPTION
            'El adicional debe pertenecer al especialista asignado.';
    END IF;

    IF TG_OP = 'UPDATE' THEN
        IF NEW.medical_request_id IS DISTINCT FROM OLD.medical_request_id
           OR NEW.specialist_profile_id IS DISTINCT FROM OLD.specialist_profile_id
           OR NEW.concept IS DISTINCT FROM OLD.concept
           OR NEW.justification IS DISTINCT FROM OLD.justification
           OR NEW.amount IS DISTINCT FROM OLD.amount
           OR NEW.currency IS DISTINCT FROM OLD.currency
           OR NEW.created_at IS DISTINCT FROM OLD.created_at
        THEN
            RAISE EXCEPTION
                'Los datos economicos y descriptivos del adicional son inmutables.';
        END IF;

        IF OLD.status <> 'PENDING' THEN
            RAISE EXCEPTION
                'Un adicional resuelto no puede modificarse. Estado actual: %.',
                OLD.status;
        END IF;

        IF NEW.status NOT IN (
            'APPROVED',
            'REJECTED',
            'WITHDRAWN'
        ) THEN
            RAISE EXCEPTION
                'Transicion de adicional no permitida: % -> %.',
                OLD.status,
                NEW.status;
        END IF;

        NEW.updated_at := NOW();
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validate_medical_request_additional
BEFORE INSERT OR UPDATE
ON medical_request_additionals
FOR EACH ROW
EXECUTE FUNCTION validate_medical_request_additional();

CREATE OR REPLACE FUNCTION prevent_finish_with_pending_additionals()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.status = 'FINALIZADO'
       AND OLD.status IS DISTINCT FROM NEW.status
       AND EXISTS (
            SELECT 1
            FROM medical_request_additionals additional
            WHERE additional.medical_request_id = NEW.id
              AND additional.status = 'PENDING'
       )
    THEN
        RAISE EXCEPTION
            'La solicitud % tiene adicionales pendientes de decision.',
            NEW.id;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_prevent_finish_with_pending_additionals
BEFORE UPDATE OF status
ON medical_requests
FOR EACH ROW
EXECUTE FUNCTION prevent_finish_with_pending_additionals();
