CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS professions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(80) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    college_acronym VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS medical_services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profession_id BIGINT NOT NULL,
    code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(220) NOT NULL,
    requires_prescription BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_medical_services_profession
        FOREIGN KEY (profession_id) REFERENCES professions(id),
    CONSTRAINT uq_medical_services_profession_code
        UNIQUE (profession_id, code)
);

INSERT INTO roles (code, name, active)
VALUES
    ('PACIENTE', 'Paciente', TRUE),
    ('ESPECIALISTA', 'Especialista', TRUE),
    ('ADMIN', 'Administrador de Sistemas', TRUE)
ON CONFLICT (code) DO NOTHING;

INSERT INTO professions (code, name, college_acronym, active)
VALUES
    ('MEDICO_GENERAL', 'Medico General', 'CMP', TRUE),
    ('ENFERMERIA', 'Enfermeria', 'CEP', TRUE),
    ('TERAPIA_FISICA_REHABILITACION', 'Terapia Fisica y Rehabilitacion', 'CTMP', TRUE),
    ('PSICOLOGIA', 'Psicologia', 'CPsP', TRUE)
ON CONFLICT (code) DO NOTHING;

INSERT INTO medical_services (profession_id, code, name, requires_prescription, active)
SELECT p.id, x.code, x.name, x.requires_prescription, TRUE
FROM professions p
JOIN (
    VALUES
    ('MEDICO_GENERAL', 'CONSULTA_MEDICA_GENERAL', 'Consulta medica general', FALSE),
    ('MEDICO_GENERAL', 'CONTROL_ENFERMEDADES_CRONICAS', 'Control de enfermedades cronicas', FALSE),
    ('MEDICO_GENERAL', 'LECTURA_INTERPRETACION_EXAMENES', 'Lectura e interpretacion de examenes', FALSE),
    ('MEDICO_GENERAL', 'CERTIFICACIONES_MEDICAS_DESCANSOS', 'Certificaciones medicas y descansos', FALSE),
    ('MEDICO_GENERAL', 'EVALUACION_PRE_POST_OPERATORIA', 'Evaluacion pre/postoperatoria', FALSE),
    ('MEDICO_GENERAL', 'CUIDADOS_PALIATIVOS_DOMICILIARIOS', 'Cuidados paliativos domiciliarios', FALSE),

    ('ENFERMERIA', 'ADMINISTRACION_TRATAMIENTOS', 'Administracion de tratamientos, inyectables o vias EV con receta', TRUE),
    ('ENFERMERIA', 'CURACION_HERIDAS_ESCARAS', 'Curacion de heridas y escaras', FALSE),
    ('ENFERMERIA', 'MONITOREO_FUNCIONES_VITALES', 'Monitoreo de funciones vitales', FALSE),
    ('ENFERMERIA', 'COLOCACION_MANEJO_SONDAS', 'Colocacion y manejo de sondas nasogastrica o vesical', TRUE),
    ('ENFERMERIA', 'HIGIENE_CONFORT_PACIENTE', 'Higiene y confort del paciente dependiente', FALSE),
    ('ENFERMERIA', 'CONSEJERIA_INMUNIZACIONES', 'Consejeria e inmunizaciones', FALSE),

    ('TERAPIA_FISICA_REHABILITACION', 'REHABILITACION_TRAUMATOLOGICA', 'Rehabilitacion traumatologica', FALSE),
    ('TERAPIA_FISICA_REHABILITACION', 'TERAPIA_FISICA_NEUROLOGICA', 'Terapia fisica neurologica', FALSE),
    ('TERAPIA_FISICA_REHABILITACION', 'FISIOTERAPIA_GERIATRICA', 'Fisioterapia geriatrica', FALSE),
    ('TERAPIA_FISICA_REHABILITACION', 'TERAPIA_RESPIRATORIA_DOMICILIARIA', 'Terapia respiratoria domiciliaria', FALSE),
    ('TERAPIA_FISICA_REHABILITACION', 'MANEJO_DOLOR_MUSCULO_ESQUELETICO', 'Manejo del dolor musculo-esqueletico', FALSE),
    ('TERAPIA_FISICA_REHABILITACION', 'ERGONOMIA_REEDUCACION_POSTURAL', 'Ergonomia y reeducacion postural', FALSE),

    ('PSICOLOGIA', 'PSICOTERAPIA_CONSEJERIA_INDIVIDUAL', 'Psicoterapia y consejeria individual', FALSE),
    ('PSICOLOGIA', 'TERAPIA_APOYO_EMOCIONAL_ADULTO_MAYOR', 'Terapia de apoyo emocional al adulto mayor', FALSE),
    ('PSICOLOGIA', 'SOPORTE_PSICOLOGICO_PACIENTE_CRONICO_TERMINAL', 'Soporte psicologico al paciente cronico o terminal', FALSE),
    ('PSICOLOGIA', 'ORIENTACION_CONSEJERIA_FAMILIAR', 'Orientacion y consejeria familiar', FALSE),
    ('PSICOLOGIA', 'EVALUACION_PSICOLOGICA_BASICA', 'Evaluacion psicologica basica', FALSE)
) AS x(profession_code, code, name, requires_prescription)
ON p.code = x.profession_code
ON CONFLICT (code) DO NOTHING;