ALTER TABLE medical_services
ADD COLUMN IF NOT EXISTS display_order INT NOT NULL DEFAULT 0;

UPDATE medical_services SET display_order = 1 WHERE code = 'CONSULTA_MEDICA_GENERAL';
UPDATE medical_services SET display_order = 2 WHERE code = 'CONTROL_ENFERMEDADES_CRONICAS';
UPDATE medical_services SET display_order = 3 WHERE code = 'LECTURA_INTERPRETACION_EXAMENES';
UPDATE medical_services SET display_order = 4 WHERE code = 'CERTIFICACIONES_MEDICAS_DESCANSOS';
UPDATE medical_services SET display_order = 5 WHERE code = 'EVALUACION_PRE_POST_OPERATORIA';
UPDATE medical_services SET display_order = 6 WHERE code = 'CUIDADOS_PALIATIVOS_DOMICILIARIOS';

UPDATE medical_services SET display_order = 1 WHERE code = 'ADMINISTRACION_TRATAMIENTOS';
UPDATE medical_services SET display_order = 2 WHERE code = 'CURACION_HERIDAS_ESCARAS';
UPDATE medical_services SET display_order = 3 WHERE code = 'MONITOREO_FUNCIONES_VITALES';
UPDATE medical_services SET display_order = 4 WHERE code = 'COLOCACION_MANEJO_SONDAS';
UPDATE medical_services SET display_order = 5 WHERE code = 'HIGIENE_CONFORT_PACIENTE';
UPDATE medical_services SET display_order = 6 WHERE code = 'CONSEJERIA_INMUNIZACIONES';

UPDATE medical_services SET display_order = 1 WHERE code = 'REHABILITACION_TRAUMATOLOGICA';
UPDATE medical_services SET display_order = 2 WHERE code = 'TERAPIA_FISICA_NEUROLOGICA';
UPDATE medical_services SET display_order = 3 WHERE code = 'FISIOTERAPIA_GERIATRICA';
UPDATE medical_services SET display_order = 4 WHERE code = 'TERAPIA_RESPIRATORIA_DOMICILIARIA';
UPDATE medical_services SET display_order = 5 WHERE code = 'MANEJO_DOLOR_MUSCULO_ESQUELETICO';
UPDATE medical_services SET display_order = 6 WHERE code = 'ERGONOMIA_REEDUCACION_POSTURAL';

UPDATE medical_services SET display_order = 1 WHERE code = 'PSICOTERAPIA_CONSEJERIA_INDIVIDUAL';
UPDATE medical_services SET display_order = 2 WHERE code = 'TERAPIA_APOYO_EMOCIONAL_ADULTO_MAYOR';
UPDATE medical_services SET display_order = 3 WHERE code = 'SOPORTE_PSICOLOGICO_PACIENTE_CRONICO_TERMINAL';
UPDATE medical_services SET display_order = 4 WHERE code = 'ORIENTACION_CONSEJERIA_FAMILIAR';
UPDATE medical_services SET display_order = 5 WHERE code = 'EVALUACION_PSICOLOGICA_BASICA';

CREATE TABLE IF NOT EXISTS user_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL,
    firebase_uid VARCHAR(150) UNIQUE,
    email VARCHAR(150) NOT NULL UNIQUE,
    first_name VARCHAR(120) NOT NULL,
    last_name VARCHAR(120) NOT NULL,
    dni VARCHAR(8) NOT NULL UNIQUE,
    mobile_phone VARCHAR(20),
    landline_phone VARCHAR(20),
    address_text VARCHAR(250) NOT NULL,
    address_reference VARCHAR(250),
    latitude NUMERIC(10,7) NOT NULL,
    longitude NUMERIC(10,7) NOT NULL,
    location GEOGRAPHY(Point, 4326) GENERATED ALWAYS AS (
        ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography
    ) STORED,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT fk_user_accounts_role FOREIGN KEY (role_id) REFERENCES roles(id),
    CONSTRAINT chk_user_accounts_contact
        CHECK (
            NULLIF(TRIM(COALESCE(mobile_phone, '')), '') IS NOT NULL
            OR NULLIF(TRIM(COALESCE(landline_phone, '')), '') IS NOT NULL
        ),
    CONSTRAINT chk_user_accounts_dni CHECK (dni ~ '^[0-9]{8}$'),
    CONSTRAINT chk_user_accounts_latitude CHECK (latitude BETWEEN -90 AND 90),
    CONSTRAINT chk_user_accounts_longitude CHECK (longitude BETWEEN -180 AND 180)
);

CREATE INDEX IF NOT EXISTS idx_user_accounts_location
ON user_accounts USING GIST (location);

CREATE TABLE IF NOT EXISTS patient_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_account_id BIGINT NOT NULL UNIQUE,
    blood_type VARCHAR(10),
    allergies TEXT,
    preexisting_conditions TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_patient_profiles_user
        FOREIGN KEY (user_account_id) REFERENCES user_accounts(id)
);

CREATE TABLE IF NOT EXISTS specialist_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_account_id BIGINT NOT NULL UNIQUE,
    profession_id BIGINT NOT NULL,
    college_number VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING_VALIDATION',
    available BOOLEAN NOT NULL DEFAULT FALSE,
    rating_average NUMERIC(3,2) NOT NULL DEFAULT 0,
    rating_count INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    activated_at TIMESTAMPTZ,
    CONSTRAINT fk_specialist_profiles_user
        FOREIGN KEY (user_account_id) REFERENCES user_accounts(id),
    CONSTRAINT fk_specialist_profiles_profession
        FOREIGN KEY (profession_id) REFERENCES professions(id),
    CONSTRAINT uq_specialist_profiles_profession_college
        UNIQUE (profession_id, college_number),
    CONSTRAINT chk_specialist_profiles_status
        CHECK (status IN (
            'PENDING_VALIDATION',
            'PENDING_INTERVIEW',
            'REJECTED_INHABILITATION',
            'REJECTED_EVALUATION',
            'ACTIVE',
            'SUSPENDED'
        ))
);

CREATE TABLE IF NOT EXISTS specialist_offered_services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    specialist_profile_id BIGINT NOT NULL,
    medical_service_id BIGINT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_specialist_offered_services_profile
        FOREIGN KEY (specialist_profile_id) REFERENCES specialist_profiles(id),
    CONSTRAINT fk_specialist_offered_services_service
        FOREIGN KEY (medical_service_id) REFERENCES medical_services(id),
    CONSTRAINT uq_specialist_offered_service
        UNIQUE (specialist_profile_id, medical_service_id)
);