CREATE TABLE IF NOT EXISTS medical_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_code VARCHAR(50) NOT NULL UNIQUE,
    patient_profile_id BIGINT NOT NULL,
    medical_service_id BIGINT NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'PENDING',
    address_text VARCHAR(250) NOT NULL,
    address_reference VARCHAR(250),
    latitude NUMERIC(10,7) NOT NULL,
    longitude NUMERIC(10,7) NOT NULL,
    location GEOGRAPHY(Point, 4326) GENERATED ALWAYS AS (
        ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography
    ) STORED,
    prescription_image_url VARCHAR(500),
    patient_notes TEXT,
    estimated_amount NUMERIC(10,2) NOT NULL DEFAULT 0,
    distance_km NUMERIC(8,2),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    accepted_at TIMESTAMPTZ,
    started_route_at TIMESTAMPTZ,
    started_attention_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,

    CONSTRAINT fk_medical_requests_patient
        FOREIGN KEY (patient_profile_id) REFERENCES patient_profiles(id),

    CONSTRAINT fk_medical_requests_service
        FOREIGN KEY (medical_service_id) REFERENCES medical_services(id),

    CONSTRAINT chk_medical_requests_status
        CHECK (status IN (
            'PENDING',
            'ACCEPTED',
            'EN_CAMINO',
            'EN_ATENCION',
            'FINALIZADO',
            'CANCELADO_PACIENTE',
            'CANCELADO_ESPECIALISTA',
            'EXPIRED'
        )),

    CONSTRAINT chk_medical_requests_latitude
        CHECK (latitude BETWEEN -90 AND 90),

    CONSTRAINT chk_medical_requests_longitude
        CHECK (longitude BETWEEN -180 AND 180)
);

CREATE INDEX IF NOT EXISTS idx_medical_requests_status
ON medical_requests (status);

CREATE INDEX IF NOT EXISTS idx_medical_requests_patient
ON medical_requests (patient_profile_id);

CREATE INDEX IF NOT EXISTS idx_medical_requests_service
ON medical_requests (medical_service_id);

CREATE INDEX IF NOT EXISTS idx_medical_requests_location
ON medical_requests USING GIST (location);