CREATE TABLE IF NOT EXISTS medical_attention_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medical_request_id BIGINT NOT NULL UNIQUE,
    specialist_profile_id BIGINT NOT NULL,
    clinical_observations TEXT NOT NULL,
    diagnostic_impression TEXT,
    recommendations TEXT NOT NULL,
    indications TEXT,
    vital_signs TEXT,
    attachment_url VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ,

    CONSTRAINT fk_attention_reports_request
        FOREIGN KEY (medical_request_id) REFERENCES medical_requests(id),

    CONSTRAINT fk_attention_reports_specialist
        FOREIGN KEY (specialist_profile_id) REFERENCES specialist_profiles(id)
);

CREATE INDEX IF NOT EXISTS idx_attention_reports_request
ON medical_attention_reports (medical_request_id);

CREATE INDEX IF NOT EXISTS idx_attention_reports_specialist
ON medical_attention_reports (specialist_profile_id);