CREATE TABLE IF NOT EXISTS medical_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medical_request_id BIGINT NOT NULL UNIQUE,
    patient_profile_id BIGINT NOT NULL,
    specialist_profile_id BIGINT NOT NULL,
    amount NUMERIC(10,2) NOT NULL,
    platform_commission_percent NUMERIC(5,2) NOT NULL,
    platform_commission_amount NUMERIC(10,2) NOT NULL,
    specialist_net_amount NUMERIC(10,2) NOT NULL,
    currency VARCHAR(10) NOT NULL DEFAULT 'PEN',
    payment_method VARCHAR(40) NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'PAID',
    external_transaction_id VARCHAR(120),
    paid_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_medical_payments_request
        FOREIGN KEY (medical_request_id) REFERENCES medical_requests(id),

    CONSTRAINT fk_medical_payments_patient
        FOREIGN KEY (patient_profile_id) REFERENCES patient_profiles(id),

    CONSTRAINT fk_medical_payments_specialist
        FOREIGN KEY (specialist_profile_id) REFERENCES specialist_profiles(id),

    CONSTRAINT chk_medical_payments_status
        CHECK (status IN ('PENDING', 'PAID', 'FAILED', 'REFUNDED')),

    CONSTRAINT chk_medical_payments_method
        CHECK (payment_method IN ('SIMULATED', 'CARD', 'YAPE', 'PLIN', 'TRANSFER', 'CASH'))
);

CREATE INDEX IF NOT EXISTS idx_medical_payments_patient
ON medical_payments (patient_profile_id);

CREATE INDEX IF NOT EXISTS idx_medical_payments_specialist
ON medical_payments (specialist_profile_id);

CREATE TABLE IF NOT EXISTS specialist_wallet_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    specialist_profile_id BIGINT NOT NULL,
    medical_payment_id BIGINT NOT NULL UNIQUE,
    transaction_type VARCHAR(40) NOT NULL DEFAULT 'SERVICE_PAYMENT',
    amount NUMERIC(10,2) NOT NULL,
    currency VARCHAR(10) NOT NULL DEFAULT 'PEN',
    status VARCHAR(40) NOT NULL DEFAULT 'AVAILABLE',
    description VARCHAR(250),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_wallet_transactions_specialist
        FOREIGN KEY (specialist_profile_id) REFERENCES specialist_profiles(id),

    CONSTRAINT fk_wallet_transactions_payment
        FOREIGN KEY (medical_payment_id) REFERENCES medical_payments(id),

    CONSTRAINT chk_wallet_transactions_type
        CHECK (transaction_type IN ('SERVICE_PAYMENT', 'ADJUSTMENT', 'PAYOUT')),

    CONSTRAINT chk_wallet_transactions_status
        CHECK (status IN ('PENDING', 'AVAILABLE', 'PAID_OUT', 'CANCELLED'))
);

CREATE INDEX IF NOT EXISTS idx_wallet_transactions_specialist
ON specialist_wallet_transactions (specialist_profile_id);