CREATE TABLE IF NOT EXISTS service_ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medical_request_id BIGINT NOT NULL,
    rater_role VARCHAR(30) NOT NULL,
    patient_profile_id BIGINT NOT NULL,
    specialist_profile_id BIGINT NOT NULL,
    score INT NOT NULL,
    comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_service_ratings_request
        FOREIGN KEY (medical_request_id) REFERENCES medical_requests(id),

    CONSTRAINT fk_service_ratings_patient
        FOREIGN KEY (patient_profile_id) REFERENCES patient_profiles(id),

    CONSTRAINT fk_service_ratings_specialist
        FOREIGN KEY (specialist_profile_id) REFERENCES specialist_profiles(id),

    CONSTRAINT uq_service_rating_request_role
        UNIQUE (medical_request_id, rater_role),

    CONSTRAINT chk_service_ratings_role
        CHECK (rater_role IN ('PATIENT', 'SPECIALIST')),

    CONSTRAINT chk_service_ratings_score
        CHECK (score BETWEEN 1 AND 5)
);

CREATE INDEX IF NOT EXISTS idx_service_ratings_request
ON service_ratings (medical_request_id);

CREATE INDEX IF NOT EXISTS idx_service_ratings_specialist
ON service_ratings (specialist_profile_id);

CREATE INDEX IF NOT EXISTS idx_service_ratings_patient
ON service_ratings (patient_profile_id);