-- ============================================================
-- BLOQUE 38.1
-- Perfil comercial del especialista
-- ============================================================

-- ------------------------------------------------------------
-- 1. Precio base por servicio ofrecido
-- ------------------------------------------------------------

ALTER TABLE specialist_offered_services
    ADD COLUMN IF NOT EXISTS base_price NUMERIC(10,2);

UPDATE specialist_offered_services sos
SET base_price =
    CASE p.code
        WHEN 'MEDICO_GENERAL' THEN 90.00
        WHEN 'ENFERMERIA' THEN 70.00
        WHEN 'TERAPIA_FISICA_REHABILITACION' THEN 80.00
        WHEN 'PSICOLOGIA' THEN 85.00
        ELSE 75.00
    END
FROM specialist_profiles sp
JOIN professions p
    ON p.id = sp.profession_id
WHERE sos.specialist_profile_id = sp.id
  AND sos.base_price IS NULL;

ALTER TABLE specialist_offered_services
    ADD CONSTRAINT chk_specialist_offered_services_base_price
    CHECK (
        base_price IS NULL
        OR base_price > 0
    );

CREATE INDEX IF NOT EXISTS idx_specialist_offered_services_profile_active
    ON specialist_offered_services (
        specialist_profile_id,
        active
    );

-- ------------------------------------------------------------
-- 2. Catálogo de métodos de pago manuales
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS payment_methods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(40) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    requires_voucher BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO payment_methods (
    code,
    name,
    requires_voucher,
    active
)
VALUES
    ('CASH', 'Efectivo', FALSE, TRUE),
    ('YAPE', 'Yape', TRUE, TRUE),
    ('PLIN', 'Plin', TRUE, TRUE),
    ('TRANSFER', 'Transferencia bancaria', TRUE, TRUE)
ON CONFLICT (code) DO UPDATE
SET
    name = EXCLUDED.name,
    requires_voucher = EXCLUDED.requires_voucher,
    active = EXCLUDED.active;

-- ------------------------------------------------------------
-- 3. Configuración comercial general del especialista
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS specialist_commercial_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    specialist_profile_id BIGINT NOT NULL UNIQUE,
    mobility_policy VARCHAR(30) NOT NULL DEFAULT 'INCLUDED',
    mobility_reference_amount NUMERIC(10,2),
    commercial_notes VARCHAR(500),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_specialist_commercial_profiles_specialist
        FOREIGN KEY (specialist_profile_id)
        REFERENCES specialist_profiles(id),

    CONSTRAINT chk_specialist_commercial_profiles_mobility
        CHECK (
            (
                mobility_policy = 'SEPARATE'
                AND mobility_reference_amount IS NOT NULL
                AND mobility_reference_amount > 0
            )
            OR
            (
                mobility_policy IN (
                    'INCLUDED',
                    'NOT_AVAILABLE'
                )
                AND mobility_reference_amount IS NULL
            )
        )
);

CREATE INDEX IF NOT EXISTS idx_specialist_commercial_profiles_active
    ON specialist_commercial_profiles (
        active
    );

-- Perfil inicial conservador para especialistas existentes:
-- movilidad incluida y sin costo adicional.
INSERT INTO specialist_commercial_profiles (
    specialist_profile_id,
    mobility_policy,
    mobility_reference_amount,
    commercial_notes,
    active
)
SELECT
    sp.id,
    'INCLUDED',
    NULL,
    NULL,
    TRUE
FROM specialist_profiles sp
ON CONFLICT (specialist_profile_id) DO NOTHING;

-- ------------------------------------------------------------
-- 4. Métodos de pago aceptados por especialista
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS specialist_payment_methods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    specialist_profile_id BIGINT NOT NULL,
    payment_method_id BIGINT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_specialist_payment_methods_specialist
        FOREIGN KEY (specialist_profile_id)
        REFERENCES specialist_profiles(id),

    CONSTRAINT fk_specialist_payment_methods_payment_method
        FOREIGN KEY (payment_method_id)
        REFERENCES payment_methods(id),

    CONSTRAINT uq_specialist_payment_method
        UNIQUE (
            specialist_profile_id,
            payment_method_id
        )
);

CREATE INDEX IF NOT EXISTS idx_specialist_payment_methods_profile_active
    ON specialist_payment_methods (
        specialist_profile_id,
        active
    );

-- Método inicial conservador para perfiles existentes.
INSERT INTO specialist_payment_methods (
    specialist_profile_id,
    payment_method_id,
    active
)
SELECT
    sp.id,
    pm.id,
    TRUE
FROM specialist_profiles sp
JOIN payment_methods pm
    ON pm.code = 'CASH'
ON CONFLICT (
    specialist_profile_id,
    payment_method_id
) DO NOTHING;